# Generated by Django 2.2.19 on 2021-03-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=10)),
                ('jurusan', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL'), ('TBSM', 'TBSM')], max_length=30)),
                ('keterangan', models.CharField(choices=[('Teknik Komputer dan Jaringan', 'Teknik Komputer dan Jaringan'), ('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak'), ('Teknik Bisnis dan Sepeda Motor', 'Teknik Bisnis dan Sepeda Motor')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('jk', models.CharField(choices=[('L', 'L'), ('L', 'P')], max_length=1)),
                ('in_kelompok', models.BooleanField(default=False)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruangan', models.CharField(choices=[('RPS 2', 'RPS 2'), ('RPS 3', 'RPS 3')], max_length=5)),
                ('no_pc', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
            ],
        ),
    ]
