# Generated by Django 2.2.19 on 2021-03-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='nomor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='ruangan',
            field=models.CharField(choices=[('Lab. 1', 'Lab. 1'), ('Lab. 2', 'Lab. 2')], max_length=5),
        ),
    ]
