# Generated by Django 2.2.19 on 2021-03-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210329_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nomor',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
