# Generated by Django 2.2.19 on 2021-03-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210329_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nomor',
            field=models.IntegerField(null=True),
        ),
    ]
