# Generated by Django 2.2.19 on 2021-03-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20210329_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nomor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
