# Generated by Django 2.2.19 on 2021-03-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20210329_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='kelompok',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Asesor'),
        ),
    ]
